import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DomainsService {

	constructor() { }
	
	getScholarityDomains(){
		return [
			{ id: '0', name: 'Primaria completa' },
			{ id: '1', name: 'Secundaria completa' },
			{ id: '2', name: 'Estudiante de pregrado' },
			{ id: '3', name: 'Universidad Completa' },
			{ id: '4', name: 'Instituto Tecnico Completo' },
			{ id: '5', name: 'Estudiante de Postgrado' }
		];
	}

  getCities(department){
  	return [
	  	/*{ name : 'Amazonas', department : 'Amazonas' },
			{ name : 'Apurimac', department : 'Apurimac' },
			{ name : 'Arequipa', department : 'Arequipa' },
			{ name : 'Ayacucho', department : 'Ayacucho' },
			{ name : 'Cajamarca', department : 'Cajamarca' },
			{ name : 'Lambayeque', department : 'Lambayeque' },
			{ name : 'Chiclayo', department : 'Lambayeque' },
			{ name : 'Ancash', department : 'Ancash' },
			{ name : 'Cusco', department : 'Cusco' },
			{ name : 'Huancavelica', department : 'Huacavelica' },
			{ name : 'Junin', department : 'Junin' },
			{ name : 'Huancayo', department : 'Junin' },
			{ name : 'Huánuco', department : 'Huanuco' },
			{ name : 'Huaraz', department : 'Ancash' },
			{ name : 'Ica', department : 'Ica' },
			{ name : 'Loreto', department : 'Loreto' },
			{ name : 'Iquitos', department : 'Loreto' },
			{ name : 'Juliaca', department : 'Puno' },
			{ name : 'Lima', department : 'Lima' },
			{ name : 'Moquegua', department : 'Moquegua' },
			{ name : 'Pasco', department : 'Pasco' },
			{ name : 'Piura', department : 'Piura' },
			{ name : 'Puno', department : 'Puno' },
			{ name : 'Tacna', department : 'Tacna' },
			{ name : 'Martin	Tarapoto', department : 'San' },
			{ name : 'Libertad	Trujillo', department : 'La' },
			{ name : 'Tumbes', department : 'Tumbes' },
			{ name : 'Ucayali', department : 'Ucayali' },
			{ name : 'Nueva Cajamarca', department : 'San Martin' },
			{ name : 'Madre de Dios', department : 'Madre de Dios' }*/
			{ name : 'CHACHAPOYAS ', department: 'AMAZONAS' },
			{ name : 'BAGUA', department: 'AMAZONAS' },
			{ name : 'BONGARA', department: 'AMAZONAS' },
			{ name : 'CONDORCANQUI', department: 'AMAZONAS' },
			{ name : 'LUYA', department: 'AMAZONAS' },
			{ name : 'RODRIGUEZ DE MENDOZA', department: 'AMAZONAS' },
			{ name : 'UTCUBAMBA', department: 'AMAZONAS' },
			{ name : 'HUARAZ', department: 'ANCASH' },
			{ name : 'AIJA', department: 'ANCASH' },
			{ name : 'ANTONIO RAYMONDI', department: 'ANCASH' },
			{ name : 'ASUNCION', department: 'ANCASH' },
			{ name : 'BOLOGNESI', department: 'ANCASH' },
			{ name : 'CARHUAZ', department: 'ANCASH' },
			{ name : 'CARLOS FERMIN FITZCARRALD', department: 'ANCASH' },
			{ name : 'CASMA', department: 'ANCASH' },
			{ name : 'CORONGO', department: 'ANCASH' },
			{ name : 'HUARI', department: 'ANCASH' },
			{ name : 'HUARMEY', department: 'ANCASH' },
			{ name : 'HUAYLAS', department: 'ANCASH' },
			{ name : 'MARISCAL LUZURIAGA', department: 'ANCASH' },
			{ name : 'OCROS', department: 'ANCASH' },
			{ name : 'PALLASCA', department: 'ANCASH' },
			{ name : 'POMABAMBA', department: 'ANCASH' },
			{ name : 'RECUAY', department: 'ANCASH' },
			{ name : 'SANTA', department: 'ANCASH' },
			{ name : 'SIHUAS', department: 'ANCASH' },
			{ name : 'YUNGAY', department: 'ANCASH' },
			{ name : 'ABANCAY', department: 'APURIMAC' },
			{ name : 'ANDAHUAYLAS', department: 'APURIMAC' },
			{ name : 'ANTABAMBA', department: 'APURIMAC' },
			{ name : 'AYMARAES', department: 'APURIMAC' },
			{ name : 'COTABAMBAS', department: 'APURIMAC' },
			{ name : 'CHINCHEROS', department: 'APURIMAC' },
			{ name : 'GRAU', department: 'APURIMAC' },
			{ name : 'AREQUIPA', department: 'AREQUIPA' },
			{ name : 'CAMANA', department: 'AREQUIPA' },
			{ name : 'CARAVELI', department: 'AREQUIPA' },
			{ name : 'CASTILLA', department: 'AREQUIPA' },
			{ name : 'CAYLLOMA', department: 'AREQUIPA' },
			{ name : 'CONDESUYOS', department: 'AREQUIPA' },
			{ name : 'ISLAY', department: 'AREQUIPA' },
			{ name : 'LA UNION', department: 'AREQUIPA' },
			{ name : 'HUAMANGA', department: 'AYACUCHO' },
			{ name : 'CANGALLO', department: 'AYACUCHO' },
			{ name : 'HUANCA SANCOS', department: 'AYACUCHO' },
			{ name : 'HUANTA', department: 'AYACUCHO' },
			{ name : 'LA MAR', department: 'AYACUCHO' },
			{ name : 'LUCANAS', department: 'AYACUCHO' },
			{ name : 'PARINACOCHAS', department: 'AYACUCHO' },
			{ name : 'PAUCAR DEL SARA SARA', department: 'AYACUCHO' },
			{ name : 'SUCRE', department: 'AYACUCHO' },
			{ name : 'VICTOR FAJARDO', department: 'AYACUCHO' },
			{ name : 'VILCAS HUAMAN', department: 'AYACUCHO' },
			{ name : 'CAJAMARCA', department: 'CAJAMARCA' },
			{ name : 'CAJABAMBA', department: 'CAJAMARCA' },
			{ name : 'CELENDIN', department: 'CAJAMARCA' },
			{ name : 'CHOTA ', department: 'CAJAMARCA' },
			{ name : 'CONTUMAZA', department: 'CAJAMARCA' },
			{ name : 'CUTERVO', department: 'CAJAMARCA' },
			{ name : 'HUALGAYOC', department: 'CAJAMARCA' },
			{ name : 'JAEN', department: 'CAJAMARCA' },
			{ name : 'SAN IGNACIO', department: 'CAJAMARCA' },
			{ name : 'SAN MARCOS', department: 'CAJAMARCA' },
			{ name : 'SAN PABLO', department: 'CAJAMARCA' },
			{ name : 'SANTA CRUZ', department: 'CAJAMARCA' },
			{ name : 'CALLAO', department: 'CALLAO' },
			{ name : 'CUSCO', department: 'CUSCO' },
			{ name : 'ACOMAYO', department: 'CUSCO' },
			{ name : 'ANTA', department: 'CUSCO' },
			{ name : 'CALCA', department: 'CUSCO' },
			{ name : 'CANAS', department: 'CUSCO' },
			{ name : 'CANCHIS', department: 'CUSCO' },
			{ name : 'CHUMBIVILCAS', department: 'CUSCO' },
			{ name : 'ESPINAR', department: 'CUSCO' },
			{ name : 'LA CONVENCION', department: 'CUSCO' },
			{ name : 'PARURO', department: 'CUSCO' },
			{ name : 'PAUCARTAMBO', department: 'CUSCO' },
			{ name : 'QUISPICANCHI', department: 'CUSCO' },
			{ name : 'URUBAMBA', department: 'CUSCO' },
			{ name : 'HUANCAVELICA', department: 'HUANCAVELICA' },
			{ name : 'ACOBAMBA', department: 'HUANCAVELICA' },
			{ name : 'ANGARAES', department: 'HUANCAVELICA' },
			{ name : 'CASTROVIRREYNA', department: 'HUANCAVELICA' },
			{ name : 'CHURCAMPA', department: 'HUANCAVELICA' },
			{ name : 'HUAYTARA', department: 'HUANCAVELICA' },
			{ name : 'TAYACAJA', department: 'HUANCAVELICA' },
			{ name : 'HUANUCO', department: 'HUANUCO' },
			{ name : 'AMBO', department: 'HUANUCO' },
			{ name : 'DOS DE MAYO', department: 'HUANUCO' },
			{ name : 'HUACAYBAMBA', department: 'HUANUCO' },
			{ name : 'HUAMALIES', department: 'HUANUCO' },
			{ name : 'LEONCIO PRADO', department: 'HUANUCO' },
			{ name : 'MARA&Ntilde;ON', department: 'HUANUCO' },
			{ name : 'PACHITEA', department: 'HUANUCO' },
			{ name : 'PUERTO INCA', department: 'HUANUCO' },
			{ name : 'LAURICOCHA', department: 'HUANUCO' },
			{ name : 'YAROWILCA', department: 'HUANUCO' },
			{ name : 'ICA', department: 'ICA' },
			{ name : 'CHINCHA', department: 'ICA' },
			{ name : 'NAZCA', department: 'ICA' },
			{ name : 'PALPA', department: 'ICA' },
			{ name : 'PISCO', department: 'ICA' },
			{ name : 'HUANCAYO', department: 'JUNIN' },
			{ name : 'CONCEPCION', department: 'JUNIN' },
			{ name : 'CHANCHAMAYO', department: 'JUNIN' },
			{ name : 'JAUJA', department: 'JUNIN' },
			{ name : 'JUNIN', department: 'JUNIN' },
			{ name : 'SATIPO', department: 'JUNIN' },
			{ name : 'TARMA', department: 'JUNIN' },
			{ name : 'YAULI', department: 'JUNIN' },
			{ name : 'CHUPACA', department: 'JUNIN' },
			{ name : 'TRUJILLO', department: 'LA LIBERTAD' },
			{ name : 'ASCOPE', department: 'LA LIBERTAD' },
			{ name : 'BOLIVAR', department: 'LA LIBERTAD' },
			{ name : 'CHEPEN', department: 'LA LIBERTAD' },
			{ name : 'JULCAN', department: 'LA LIBERTAD' },
			{ name : 'OTUZCO', department: 'LA LIBERTAD' },
			{ name : 'PACASMAYO', department: 'LA LIBERTAD' },
			{ name : 'PATAZ', department: 'LA LIBERTAD' },
			{ name : 'SANCHEZ CARRION', department: 'LA LIBERTAD' },
			{ name : 'SANTIAGO DE CHUCO', department: 'LA LIBERTAD' },
			{ name : 'GRAN CHIMU', department: 'LA LIBERTAD' },
			{ name : 'VIRU', department: 'LA LIBERTAD' },
			{ name : 'CHICLAYO', department: 'LAMBAYEQUE' },
			{ name : 'FERRE&Ntilde;AFE', department: 'LAMBAYEQUE' },
			{ name : 'LAMBAYEQUE', department: 'LAMBAYEQUE' },
			{ name : 'LIMA', department: 'LIMA' },
			{ name : 'BARRANCA', department: 'LIMA' },
			{ name : 'CAJATAMBO', department: 'LIMA' },
			{ name : 'CANTA', department: 'LIMA' },
			{ name : 'CA&Ntilde;ETE', department: 'LIMA' },
			{ name : 'HUARAL', department: 'LIMA' },
			{ name : 'HUAROCHIRI', department: 'LIMA' },
			{ name : 'HUAURA', department: 'LIMA' },
			{ name : 'OYON', department: 'LIMA' },
			{ name : 'YAUYOS', department: 'LIMA' },
			{ name : 'MAYNAS', department: 'LORETO' },
			{ name : 'ALTO AMAZONAS', department: 'LORETO' },
			{ name : 'LORETO', department: 'LORETO' },
			{ name : 'MARISCAL RAMON CASTILLA', department: 'LORETO' },
			{ name : 'REQUENA', department: 'LORETO' },
			{ name : 'UCAYALI', department: 'LORETO' },
			{ name : 'TAMBOPATA', department: 'MADRE DE DIOS' },
			{ name : 'MANU', department: 'MADRE DE DIOS' },
			{ name : 'TAHUAMANU', department: 'MADRE DE DIOS' },
			{ name : 'MARISCAL NIETO', department: 'MOQUEGUA' },
			{ name : 'GENERAL SANCHEZ CERRO', department: 'MOQUEGUA' },
			{ name : 'ILO', department: 'MOQUEGUA' },
			{ name : 'PASCO', department: 'PASCO' },
			{ name : 'DANIEL ALCIDES CARRION', department: 'PASCO' },
			{ name : 'OXAPAMPA', department: 'PASCO' },
			{ name : 'PIURA', department: 'PIURA' },
			{ name : 'AYABACA', department: 'PIURA' },
			{ name : 'HUANCABAMBA', department: 'PIURA' },
			{ name : 'MORROPON', department: 'PIURA' },
			{ name : 'PAITA', department: 'PIURA' },
			{ name : 'SULLANA', department: 'PIURA' },
			{ name : 'TALARA', department: 'PIURA' },
			{ name : 'SECHURA', department: 'PIURA' },
			{ name : 'PUNO', department: 'PUNO' },
			{ name : 'AZANGARO', department: 'PUNO' },
			{ name : 'CARABAYA', department: 'PUNO' },
			{ name : 'CHUCUITO', department: 'PUNO' },
			{ name : 'EL COLLAO', department: 'PUNO' },
			{ name : 'HUANCANE', department: 'PUNO' },
			{ name : 'LAMPA', department: 'PUNO' },
			{ name : 'MELGAR', department: 'PUNO' },
			{ name : 'MOHO', department: 'PUNO' },
			{ name : 'SAN ANTONIO DE PUTINA', department: 'PUNO' },
			{ name : 'SAN ROMAN', department: 'PUNO' },
			{ name : 'SANDIA', department: 'PUNO' },
			{ name : 'YUNGUYO', department: 'PUNO' },
			{ name : 'MOYOBAMBA', department: 'SAN MARTIN' },
			{ name : 'BELLAVISTA', department: 'SAN MARTIN' },
			{ name : 'EL DORADO', department: 'SAN MARTIN' },
			{ name : 'HUALLAGA', department: 'SAN MARTIN' },
			{ name : 'LAMAS', department: 'SAN MARTIN' },
			{ name : 'MARISCAL CACERES', department: 'SAN MARTIN' },
			{ name : 'PICOTA', department: 'SAN MARTIN' },
			{ name : 'RIOJA', department: 'SAN MARTIN' },
			{ name : 'SAN MARTIN', department: 'SAN MARTIN' },
			{ name : 'TOCACHE', department: 'SAN MARTIN' },
			{ name : 'TACNA', department: 'TACNA' },
			{ name : 'CANDARAVE', department: 'TACNA' },
			{ name : 'JORGE BASADRE', department: 'TACNA' },
			{ name : 'TARATA', department: 'TACNA' },
			{ name : 'TUMBES', department: 'TUMBES' },
			{ name : 'CONTRALMIRANTE VILLAR', department: 'TUMBES' },
			{ name : 'ZARUMILLA', department: 'TUMBES' },
			{ name : 'CORONEL PORTILLO', department: 'UCAYALI' },
			{ name : 'ATALAYA', department: 'UCAYALI' },
			{ name : 'PADRE ABAD', department: 'UCAYALI' },
			{ name : 'PURUS', department: 'UCAYALI' }
  	].filter(city => city.department == department.name);
  }

  getDepartments(){
  	return [
  		{ name : 'AMAZONAS' },
			{ name : 'ANCASH' },
			{ name : 'APURIMAC' },
			{ name : 'AREQUIPA' },
			{ name : 'AYACUCHO' },
			{ name : 'CAJAMARCA' },
			{ name : 'CALLAO' },
			{ name : 'CUSCO' },
			{ name : 'HUANCAVELICA' },
			{ name : 'HUANUCO' },
			{ name : 'ICA' },
			{ name : 'JUNIN' },
			{ name : 'LA LIBERTAD' },
			{ name : 'LAMBAYEQUE' },
			{ name : 'LIMA' },
			{ name : 'LORETO' },
			{ name : 'MADRE DE DIOS' },
			{ name : 'MOQUEGUA' },
			{ name : 'PASCO' },
			{ name : 'PIURA' },
			{ name : 'PUNO' },
			{ name : 'SAN MARTIN' },
			{ name : 'TACNA' },
			{ name : 'TUMBES' },
			{ name : 'UCAYALI' }
	    /*{ name : 'Amazonas' },
	    { name : 'Apurimac' },
	    { name : 'Arequipa' },
	    { name : 'Ayacucho' },
	    { name : 'Cajamarca' },
	    { name : 'Lambayeque' },
	    { name : 'Ancash' },
	    { name : 'Cusco' },
	    { name : 'Huacavelica' },
	    { name : 'Junin' },
	    { name : 'Huanuco' },
	    { name : 'Ica' },
	    { name : 'Loreto' },
	    { name : 'Puno' },
	    { name : 'Lima' },
	    { name : 'Madre de Dios' },
	    { name : 'Moquegua' },
	    { name : 'San Martin' },
	    { name : 'Pasco' },
	    { name : 'Piura' },
	    { name : 'Tacna' },
	    { name : 'La Libertad' },
	    { name : 'Tumbes' },
	    { name : 'Ucayali' }*/
	  ];
  }
}
